### ISSUE TITLE
Podspec install errors: no tag/branch for package version

### ISSUE THREAD

**Issue by lindboe** [react-native-community/react-native-masked-view#16]
# Bug

I just tried to add this library to my project, and in the Podfile I added `pod 'RNCMaskedView', :podspec => '../node_modules/@react-native-community/masked-view/RNCMaskedView.podspec'`. When running `pod install`, I get the following error:

```
[!] Error installing RNCMaskedView
[!] /usr/local/bin/git clone https://github.com/react-native-community/react-native-masked-view.git /var/folders/70/58j390s50ms671frlskkd_9r0000gn/T/d20190724-13772-pjtr1t --template= --single-branch --depth 1 --branch v0.1.1

...
warning: Could not find remote branch v0.1.1 to clone.
fatal: Remote branch v0.1.1 not found in upstream origin
```
With further research, I confirmed this error will show if the tag is missing as well.

I found https://github.com/react-native-community/react-native-masked-view/pull/10 which changed the Podspec to look for a tag with the current version, which _should_ be correct, but this repo does not have versioned tags or branches at the moment, so I'm unsure how this is intended to work.

### Workaround

Instead of the above line in the Podfile, you can use `pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'`. Using `:path` instead of the podspec will install from the on-disk copy, but this is only intended for when you're locally developing on a pod dependency simultaneously.

## Environment info

React native info output:

```bash
  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
      Memory: 1.53 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.1.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.8 => 0.59.8
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-macos-cli: 2.0.1
```

Library version: 0.1.1

## Steps To Reproduce

1. Add react-native-masked-view to a Podfile-based react-native project
2. Add `pod 'RNCMaskedView', :podspec => '../node_modules/@react-native-community/masked-view/RNCMaskedView.podspec'` to Podfile
3. Run `pod install`

Describe what you expected to happen:

Library installed without errors.

**Comment by FonDorn** [comment]
If you are using React Native < 0.60 then you need only linked the library into project (`react-native link @react-native-community/masked-view`), no need to add RNCMaskedView into pod file. For React Native >= 0.60 use `cd ios && pod install` after install lib.

**Comment by Evan-Younan** [comment]
Just had the same issue after installing 0.1.5. It seems like the **pod** file is not being updated when the dependency is installed. That's why it has to be manually added into the pod file before performing the pod install.

**Comment by koenpunt** [comment]
> If you are using React Native < 0.60 then you need only linked the library into project (`react-native link @react-native-community/masked-view`), no need to add RNCMaskedView into pod file. For React Native >= 0.60 use `cd ios && pod install` after install lib.

This is only true when you're using a standard (greenfield) installation. I for example use this library in a brownfield application, which is not using autolinking, and thus requires tags to be present. 

If tags are not going to be created for every release, can we then please update the podspec to not refer to a tag, but to a branch (`master`) instead?

**Comment by kirankbee** [comment]
I am on RN >=.60 
i get this warning 
[!] use_native_modules! skipped the react-native dependency 'react-native-masked-view'. No podspec file was found.
any tips to overcome ?
