### ISSUE TITLE
Set BackgroundColor of maskElement

### ISSUE THREAD

**Issue by karvulf** [react-native-community/react-native-masked-view#23]
# Feature Request

Currently you can only have the white _backgroundColor_ of the `maskElement`. It would be nice, if you could change the color.

### Code sample

Try the example. You can see that it get's the white _backgroundColor_. It's only possible to change the alpha-value.

**Comment by karvulf** [comment]
Oh I had to set the backgroundColor of my parents view to get the backgroundColor. I'm closing this issue.

**Comment by CezarCobuz** [comment]
I think I am facing the same issue, can't get the background color changed on the mask. Would you be so kind to provide an example on how to change the background color of the mask?

**Comment by liqueflies** [comment]
Can I see some examples of how to do that?
Also me if wrapping MaskView with a View and a backgroundColor is not working :(

**Comment by AdarshJais** [comment]
> Having the same issues and wrapping the `MaskedView` in a parent view with a set background color is not fixing the issue. I'm making a rectangle with a curved top/edge and the corners (the cutout areas in my mask) are solid white. No combination of transparent / `rgba(x, x, x, 0.0)` is working.

Did you get any solution for the same? Facing the same issue
