### ISSUE TITLE
MaskedView with LinearGradient not working on Android

### ISSUE THREAD

**Issue by bhavesh-trentium** [react-native-community/react-native-masked-view#235]
I am using a `MaskedView `and `LinearGradient`. To create a GradientText its working well on iOS but on a Android not.
On an Android, it shows a Red Color Background.
Not sure but it's an issue created MaskedView Related. MaskedView is not working on Android.

```
import { LinearGradient } from 'expo-linear-gradient';
import MaskedView from '@react-native-masked-view/masked-view';

 <MaskedView maskElement={<Text style={style}>{text}</Text>}>
      <LinearGradient
        start={{ x: 0, y: 0 }}
        end={{ x: 1, y: 1 }}
        colors={textColor}>
        <Text style={[style, { opacity: 0 }]}>{text}</Text>
      </LinearGradient>
    </MaskedView>
```

  ```
    "react-native": "0.72.6",
    "expo": "^49.0.21",
    "expo-linear-gradient": "~12.3.0",
    "@react-native-masked-view/masked-view": "0.2.9",
```
### ANDROID
![screenshot_2024-11-14-16-27-15-433_io smatchit app_720](https://github.com/user-attachments/assets/9973cae0-0aac-4d66-a083-1d3af75c8231)

### iOS
![image](https://github.com/user-attachments/assets/607a3a07-bd10-404a-899c-2b79fad2b71e)

**Comment by akshay-mob123** [comment]
Do u find any other way?

**Comment by bhavesh-trentium** [comment]
@akshay-mob123 In an `app.json` remove this line or false it. after that is fixed
`"newArchEnabled": true`

**Comment by DavitVosk** [comment]
@bhavesh-trentium I see you found a way to make it work for you... On my side color is working, but it is somehow blurred if compared with IOS one. Did you have such problem on your side please?

**Comment by DavitVosk** [comment]
I found the solution: we need to have some dummy color here to be able to show non-blurred colors on Android: `maskElement={<Text {...props} style={[props.style, {color: theme.colors.black}]} />}`
