### ISSUE TITLE
MaskedView support for Android

### ISSUE THREAD

**Issue by cpojer** [react-native-community/react-native-masked-view#3]
* * *
  This issue was originally created by @IljaDaderko as facebook/react-native#19546.
  * * *

  ## For Discussion
I've worked on view demonstrated below today, very pleasant experience while using [MaskedViewIOS](https://facebook.github.io/react-native/docs/maskedviewios.html)
In essence it masks Orc graphic with that dark cloud / smoky mask. On android however, I was not able to find anything similar from community and after 3h of trying to create a native component bridge for this, I came nowhere close :/

Hence I wanted to start this discussion, shall we make `MaskedView` more general and support it for Android as well, or are there some limitations that don't allow this (hence only IOS implementation at the moment?)

<img width="314" alt="screen shot 2018-06-03 at 14 55 47" src="https://user-images.githubusercontent.com/3154053/40886319-386c22a4-673e-11e8-9b15-d896a5ff5ed7.png">

**Comment by Bunlong** [comment]
@cpojer `MaskedView` should be made more general and support it for Android as well. This would be great to have `MaskedView` for Android :+1:

**Comment by dalmarcogd** [comment]
+ 1

**Comment by RWOverdijk** [comment]
Yes please. Perhaps a similar approach as suggested in the previous issue would be nice?

https://github.com/facebook/react-native/issues/19546#issuecomment-450597954

**Comment by Noitidart** [comment]
I would thinkgit would be ok iOS having some extras and Android having some extras. It will help fine tune for the platform look and feel. But the goal is similar so it would be nice to see in one package.

**Comment by AlexandreLage** [comment]
I managed to accomplish this for both Android and iOS using Svg masking features.
See 'expo svg'
