### ISSUE TITLE
React-Native app not running

### ISSUE THREAD

**Issue by TarunPandat** [react-native-community/react-native-masked-view#40]
I created a react-native app in my system and I upload it on git and send a link to my friend but that app not working in his system I also run npm install cmd but still getting the same issue. I'm using ubuntu and he is using windows maybe this is the reason of error, Please help me to solve this issue.

The error is...

C:\Users\shiv\Desktop\prabhubhakti>react-native run-androidinfo Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.Jetifier found 1340 file(s) to forward-jetify. Using 4 workers...info JS server already running.info Launching emulator...error Failed to launch emulator. Reason: Could not start emulator within 30 seconds..warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.info Installing the app...> Task :@react-native-community_masked-view:generateDebugBuildConfig FAILED2 actionable tasks: 2 executedFAILURE: Build failed with an exception.* What went wrong:Execution failed for task ':@react-native-community_masked-view:generateDebugBuildConfig'.> java.io.IOException: Unable to delete directory C:\Users\shiv\Desktop\prabhubhakti\node_modules\@react-native-community\masked-view\android\build\generated\source\buildConfig\debug\org.* Try:Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get morelog output. Run with --scan to get full insights.* Get more help at https://help.gradle.orgBUILD FAILED in 4m 24serror Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081FAILURE: Build failed with an exception.* What went wrong:Execution failed for task ':@react-native-community_masked-view:generateDebugBuildConfig'.> java.io.IOException: Unable to delete directory C:\Users\shiv\Desktop\prabhubhakti\node_modules\@react-native-community\masked-view\android\build\generated\source\buildConfig\debug\org.* Try:Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get morelog output. Run with --scan to get full insights.* Get more help at https://help.gradle.orgBUILD FAILED in 4m 24s    at checkExecSyncError (child_process.js:616:11)    at execFileSync (child_process.js:634:13)    at runOnAllDevices (C:\Users\shiv\Desktop\prabhubhakti\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:39)ReplyForward |   | ReplyForward |   |  
-- | -- | -- | -- | --
  | ReplyForward

**Comment by FonDorn** [comment]
This is not library issue. Just look for [this](https://stackoverflow.com/a/42707592/5442674) answer.

**Comment by TarunPandat** [comment]
Thanks..
