### ISSUE TITLE
./grandlew assembleDebug, error RNCMaskedViewPackage is not abstract and does not override abstract method createJSModules()

### ISSUE THREAD

**Issue by DanielRiera** [react-native-community/react-native-masked-view#43]
# Bug

Have this error when i run "./grandlew assembleDebug"

..../node_modules/@react-native-community\masked-view\android\src\main\java\org\reactnative\maskedview\RNCMaskedViewPackage.java:13: error: RNCMaskedViewPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNCMaskedViewPackage implements ReactPackage {
1 error

## Environment info

React native info output:

```bash
System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Memory: 6.24 GB / 15.91 GB
  Binaries:
    Node: 10.16.2
    Yarn: 1.21.1
    npm: 6.9.0
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245
react-native-community/masked-view 0.1.6 version
react-native version 3.0.4
sdkVersion 36.0.0
```

## Steps To Reproduce

1. Execute ./grandlew assembleDebug

Describe what you expected to happen:

Compile

**Comment by FonDorn** [comment]
You have a typo ./gra**n**dlew -> ./grandlew
Also I run `./grandlew assembleDebug` in new project with masked view module and have not errors

**Comment by DanielRiera** [comment]
Yes @FonDorn Sorry, It's a typo when I published the issue on GitHub, i run ./gradlew assembleDebug and have same error.

Thanks

**Comment by DanielRiera** [comment]
Solved:
Add this to ./node_modules/@react-native-community\masked-view\android\src\main\java\org\reactnative\maskedview\RNCMaskedViewPackage.java

`@Override
  public List<Class<? extends JavaScriptModule>> createJSModules() {
    return Collections.emptyList();
  }`
