### ISSUE TITLE
'RCTUIManager.h' file not found

### ISSUE THREAD

**Issue by franzwarning** [react-native-community/react-native-masked-view#5]
Getting this issue on line 11 of `RNCMaskedViewManager.m`. Deleting this line works, and the build succeeds.

Versions:
- react-native: 0.59.0
- @react-native-community/masked-view: ^0.0.1
- react: 16.8.3

**Comment by zsaraf** [comment]
Having this exact same issue!

**Comment by FonDorn** [comment]
Thanks for this issue. Fixed in 0.0.2 version (#6)
