### ISSUE TITLE
RN project startup spent too much time (doubt is @ the react - native - community/masked - the view, but not sure)

### ISSUE THREAD

**Issue by ACDC5** [react-native-community/react-native-masked-view#54]
package.json:
dependencies: {
    "@react-native-community/masked-view": "^0.1.7",
    "@react-navigation/bottom-tabs": "^5.2.5",
    "@react-navigation/native": "^5.1.4",
    "@react-navigation/stack": "^5.2.9",
    "react": "16.11.0",
    "react-native": "0.62.0",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.7.1",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.4.0"
  }

I started the project using NPX react-native run-android

It takes a long time to get to this step, which is painful;
![RN_11111](https://user-images.githubusercontent.com/43377515/78334548-868f5d80-75be-11ea-9ba7-7c7b9d3780f6.png)
Sometimes I need to spend half an hour or more here

Looking forward to your Suggestions?
thank you

**Comment by kevinwebiots** [comment]
same thing is happening with me did you got any solution ?

**Comment by ACDC5** [comment]
> same thing is happening with me did you got any solution ?
Unfortunately there is still no progress, I am trying to reduce the version of this dependency

**Comment by FonDorn** [comment]
@ACDC5 check it on version `0.1.9`.

**Comment by ACDC5** [comment]
@FonDorn 
Now start the project normal, I upgraded the @ the react - native - community/masked - view to 0.1.9
Thank you very much
