### ISSUE TITLE
Impossible to update a dynamic Text 

### ISSUE THREAD

**Issue by IlanZ93** [react-native-community/react-native-masked-view#67]
Hello, 

I have a progress bar so i use MaskedView for change the color of my text following the progress bar.

It work well on iOS, but on Android my text dont change.

This issue is quit the same as this one : #19 

It says that the issue is closed because 'this issue has been resolved in the newest release' but i still have this problem so do you have any solution ? 

Thank you

**Comment by raajnadar04** [comment]
Hey how did you solve this?
